### ISSUE TITLE
Some encounter tables match Crystal but not Gold or Silver.

### ISSUE THREAD

**Issue by RobSp1derp1g** [pret/pokegold#16]
https://github.com/pret/pokegold/blob/master/data/wild/johto_grass.asm#L1299

In this specific case, the encounter table for Route 33 matches Crystal, but not Gold or Silver.
This is the only issue I have so far.

**Comment by iimarckus** [comment]
This is basically covered by #13.

pokegold is quite far from being finished. Things are progressing, but slowly…

**Comment by entrpntr** [comment]
As of a0ebc7f, encounter tables now match Gold/Silver data.
