### ISSUE TITLE
Items to address once disassembly is complete

### ISSUE THREAD

**Issue by entrpntr** [pret/pokegold#47]
Placeholder for things we'll want to address soon after disassembly is complete and the baseroms are no longer required. We'll want to complete these tasks before any other changes are made to the repo. (Using pokegold for asm-based hacks also isn't recommended until these are complete.)

- [x] Add Travis CI files
- [x] Update INSTALL.md to remove instructions about baserom requirement
- [x] Remove unnecessary tools / `dr` macro
- [x] Ensure there are no remaining artifacts that interfere with shiftability, etc.
- [x] Make decision on whether or not to sync macros/legacy.asm with pokecrystal
- [x] Setup toolchain for building binary gfx files from PNGs (see #31)

(Will add more, if/when necessary.)

**Comment by Rangi42** [comment]
Regarding macros/legacy.asm: the audio macros are useful since many music .asm files exist using older ones, and if pokegold+pokecrystal share some legacy macros, they may as well share all of them. It could help with porting some projects' data between versions.

**Comment by Rangi42** [comment]
Three binary gfx files remain:

- [ ] gfx/pokemon/alakazam/back_silver.2bpp.lz.bin
- [ ] gfx/title/hooh_gold.2bpp.lz.bin
- [ ] gfx/title/lugia_silver.2bpp.lz.bin

Alakazam's back sprite can't be matched, so will have to stay as-is with an explanatory comment. The title graphics are probably matchable.

**Comment by Rangi42** [comment]
@entrpntr I expect that the last point "Ensure there are no remaining artifacts that interfere with shiftability, etc" is also not an issue; you can close this if there's nothing else you wanted to address. =)
