### ISSUE TITLE
Build the debug ROMs

### ISSUE THREAD

**Issue by Rangi42** [pret/pokegold#53]
Currently being disassembled by @libjet here: https://github.com/libjet/pokegold-debug

> It builds the following ROM:
>
> - MONSGD.gbc `sha1: 539245e162123ceac77f0615e0eabddd8efb8b7d`
>
> The original build date is the 3rd February 2000, at 21:50 and the ROM was leaked on the 11th April 2020
> 
> *Silver TBD

A `golddebug` target that passes `-D _DEBUG` should work, since this is presumably the final release simply with Game Freak's debug build flag enabled. (Or `-D _GSDEBUG` to clarify that it's an "official" debug ROM, not a pret debugging feature.)

**Comment by Rangi42** [comment]
Actually, those are Japanese debug ROMs; we may not have any English ones.

**Comment by mid-kid** [comment]
`mons2/final_rom/mons2_gld_ps3_debug.bin`
`mons2/final_rom/mons2_slv_ps3_debug.bin`

**Comment by mid-kid** [comment]
But yeah, libjet's efforts are towards the japanese debug roms.
