### ISSUE TITLE
Missing file (?)

### ISSUE THREAD

**Issue by tsakalov** [pret/pokegold#7]
It does not find "common_gold.o" in order to make gold rom. The following message appears after make:
 
$ make
make: *** No rule to make target 'baserom-gold.gbc', needed by 'data/text/common_gold.o'.  Stop.

I have seen that this has been asked already but there has not been any resolution to this issue.

**Comment by ISSOtm** [comment]
You need base roms to build the project, as described [here](https://github.com/pret/pokegold/blob/master/INSTALL.md#notice).

**Comment by tsakalov** [comment]
My bad. I did not pay attention to that step..
I feel ashamed for being so careless.
Thank you for your immediate reply.
